version: "3.1"

services:
  app:
    container_name: metro-town-app
    build: .
    ports:
      - 8081:80
    depends_on:
      - mongo
  mongo:
    container_name: metro-town-mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: pony_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
